package net.petrikainulainen.testproject;

import io.testproject.java.annotations.v2.Parameter;
import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.ParameterDirection;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import io.testproject.proxy.addon.BlogSearchAddon;
import io.testproject.proxy.addon.net.petrikainulainen.testproject.addon.BlogSearchAction;
import io.testproject.proxy.addon.net.petrikainulainen.testproject.addon.ClearBlogSearchFieldAction;
import java.lang.String;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: Tests for My Website 3
 * Test: Exported Blog Search Test
 * Generated by: Petri Kainulainen (petri@petrikainulainen.net)
 * Generated on Thu Apr 25 16:45:05 GMT 2019.
 */
@Test(
    name = "Exported Blog Search Test",
    version = "1.0"
)
public class ExportedBlogSearchTest implements WebTest {
  @Parameter(
      description = "Auto generated application URL parameter",
      defaultValue = "https://www.petrikainulainen.net/blog/",
      direction = ParameterDirection.INPUT
  )
  public String ApplicationURL;

  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    ClearBlogSearchFieldAction clearBlogSearchFieldAction;
    boolean booleanResult;
    BlogSearchAction blogSearchAction;
    ExecutionResult executionResult;

    // 1. Navigate to 'https://www.petrikainulainen.net/blog/'
    //    Navigates the specified URL (Auto-generated)
    booleanResult = driver.testproject().navigateToUrl(ApplicationURL);
    report.step("Navigate to 'https://www.petrikainulainen.net/blog/'", booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Run Clear the search field of the search form
    clearBlogSearchFieldAction = BlogSearchAddon.getClearBlogSearchFieldAction();
    executionResult = helper.executeProxy(clearBlogSearchFieldAction);
    report.step("Run Clear the search field of the search form", executionResult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 3. Run Enter the search term and submit the search form
    blogSearchAction = BlogSearchAddon.blogSearchAction("junit 5");
    executionResult = helper.executeProxy(blogSearchAction);
    report.step("Run Enter the search term and submit the search form", executionResult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 4. 'H1' contains text 'Search: junit 5'?
    by = By.xpath("//*[@id='content_box']/div/div[1]/div[1]/h1");
    booleanResult = driver.testproject().containsText(by,"Search: junit 5");
    report.step("'H1' contains text 'Search: junit 5'?", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
