package net.petrikainulainen.testproject;

import io.testproject.java.enums.AutomatedBrowserType;
import io.testproject.java.execution.results.StepExecutionResult;
import io.testproject.java.sdk.v2.Runner;
import java.lang.Exception;
import java.lang.String;

/**
 * This class was automatically generated by TestProject
 * Provides an example how to run coded TestProject tests
 */
public class TestsForMyWebsite3Runner {
  public static String developerToken = "qiK0J1WPg_xeA8aqtsq2qzshoMifaeIvJhg7SLLEMio1";

  public static AutomatedBrowserType browserType = AutomatedBrowserType.Chrome;

  public static void main(String[] args) {
    try {
      runExportedBlogSearchTest();
    }
    catch (Exception e) {
    }
  }

  /**
   * Runs "ExportedBlogSearchTest"
   */
  public static StepExecutionResult runExportedBlogSearchTest() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new ExportedBlogSearchTest(), true);
  }
}
