package net.petrikainulainen.testproject;

import io.testproject.java.enums.AutomatedBrowserType;
import io.testproject.java.execution.results.StepExecutionResult;
import io.testproject.java.sdk.v2.Runner;
import java.lang.Exception;
import java.lang.String;

/**
 * This class was automatically generated by TestProject
 * Provides an example how to run coded TestProject tests
 */
public class TestsForMyWebsite3Runner {

  //If you want to run the exported test by using this runner, go to the Developers
  //page of the app.testproject.io website and use your developer key.
  public static String developerToken = "REPLACE_THIS_WITH_YOUR_DEVELOPMENT_KEY";

  public static AutomatedBrowserType browserType = AutomatedBrowserType.Chrome;

  public static void main(String[] args) {
    try {
      runExportedBlogSearchTest();
    }
    catch (Exception e) {
    }
  }

  /**
   * Runs "ExportedBlogSearchTest"
   */
  public static StepExecutionResult runExportedBlogSearchTest() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new ExportedBlogSearchTest(), true);
  }
}
